version: '3.8'

services:
  arbor-backend:
    build: .
    container_name: arbor_backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
